package com.jianma.fzkb.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name = "material", catalog = "sdx_fzkb")
public class Material implements java.io.Serializable {

	private Integer id;
	private String name;
	private String thumb;
	private String masterImage;
	private String categoryName;
	private String style1;
	private String style2;
	private String style3;
	private Date createTime;

	public Material() {
	}

	public Material(int id,String name, String thumb, String masterImage, String categoryName, String style1, String style2,
			String style3, Date createTime) {
		this.id = id;
		this.name = name;
		this.thumb = thumb;
		this.masterImage = masterImage;
		this.categoryName = categoryName;
		this.style1 = style1;
		this.style2 = style2;
		this.style3 = style3;
		this.createTime = createTime;
	}
	
	public Material(String name, String thumb, String masterImage, String categoryName, String style1, String style2,
			String style3, Date createTime) {
		this.name = name;
		this.thumb = thumb;
		this.masterImage = masterImage;
		this.categoryName = categoryName;
		this.style1 = style1;
		this.style2 = style2;
		this.style3 = style3;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "thumb", nullable = false)
	public String getThumb() {
		return this.thumb;
	}

	public void setThumb(String thumb) {
		this.thumb = thumb;
	}

	@Column(name = "masterImage", nullable = false)
	public String getMasterImage() {
		return this.masterImage;
	}

	public void setMasterImage(String masterImage) {
		this.masterImage = masterImage;
	}

	@Column(name = "categoryName", nullable = false, length = 10)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "style1", nullable = false, length = 10)
	public String getStyle1() {
		return this.style1;
	}

	public void setStyle1(String style1) {
		this.style1 = style1;
	}

	@Column(name = "style2", nullable = false, length = 10)
	public String getStyle2() {
		return this.style2;
	}

	public void setStyle2(String style2) {
		this.style2 = style2;
	}

	@Column(name = "style3", nullable = false, length = 10)
	public String getStyle3() {
		return this.style3;
	}

	public void setStyle3(String style3) {
		this.style3 = style3;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
